thickarrow_strings = (               #sized 24x24
  "XX                      ",
  "XXX                     ",
  "XXXX                    ",
  "XX.XX                   ",
  "XX..XX                  ",
  "XX...XX                 ",
  "XX....XX                ",
  "XX.....XX               ",
  "XX......XX              ",
  "XX.......XX             ",
  "XX........XX            ",
  "XX........XXX           ",
  "XX......XXXXX           ",
  "XX.XXX..XX              ",
  "XXXX XX..XX             ",
  "XX   XX..XX             ",
  "     XX..XX             ",
  "      XX..XX            ",
  "      XX..XX            ",
  "       XXXX             ",
  "       XX               ",
  "                        ",
  "                        ",
  "                        ")

dialogue_strings = (
  "    XXXXXXXXXXXXXXXX    ",
  "   X................X   ",
  "  X..................X  ",
  "  X..................X  ",
  "  X..................X  ",
  "  X..................X  ",
  "  X..................X  ",
  "  X..................X  ",
  "  X..................X  ",
  "  X..................X  ",
  "  X..................X  ",
  "  X..................X  ",
  "   X................X   ",
  "    XX..XXXXXXXXXXXX    ",
  "     XX..XX             ",
  "       XX               ",
  "                        ",
  "                        ",
  "                        ",
  "                        ",
  "                        ",
  "                        ",
  "                        ",
  "                        ")