from csv_transformer import *
# Paramètres du jeu
WIDTH, HEIGHT = 1280, 720 #Longueur
FPS = 60
GRAVITY = 1.8
TILE_SIZE=32

#ui main menu

BUT_SIZE= {"x": 250, "y": 30}
IG_MENU_SIZE=(250,250)

#ui setup world
UI_FONT="Coding/graphics/font/times.ttf"
UI_FONT_SIZE=30

ITEM_BOX_SIZE=80

HEALTH_BAR_HEIGHT=20
HEALTH_BAR_WIDTH=200

XP_BAR_HEIGHT=20
XP_BAR_WIDTH=200

ENERGY_BAR_HEIGHT=20
ENERGY_BAR_WIDTH=200

#color setup

GREEN=(0,255,0)
BLUE=(0,0,255)
BLUEXP=(0,0,100)
YELLOW=(255,255,0)

#player
PLAYER_RUNNING_SPEED_MULTIPLICATOR=6
PLAYER_JUMP_MULTIPLICATOR  = 3
PLAYER_SPEED_MULTIPLICATOR = 5
WALL_JUMP_X_SPEED_MULTIPLICATOR=2
WALL_JUMP_COOLDOWN=200
JUMP_COOLDOWN=200
MAXJUMP=200
MAX_HEALTH=100

# Entite 
ENTITE_SPEED_MULTIPLICATOR=5

# Monstre


#Spectre


VOID_CHR=" "

#map setup

WORLD_MAP = csv_to_list('Coding/graphics/tilemap/ground/fichiers_csv/_non visible.csv')
